services:
  onboarding-app:
    build:
      context: ./app
    depends_on:
      - onboarding-database
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      - 35729:35729
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./app
          target: /usr/src/app
          action: sync

  onboarding-database:
    image: mongo:6
    command: ["mongod", "--replSet", "rs0"]  # Set MongoDB to run as a replica set
    volumes:
      - database:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""

volumes:
  database:
